var JsonObj=[];

var data={};
data["itemName"]="Item1";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=40;
data["rating"]=2.4;
data["secRating"]=3.4;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item2";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=90;
data["rating"]=3.2;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item3";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=0.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item4";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=4.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item5";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=4.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item6";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=4.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item7";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=4.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item8";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=4.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item9";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Bangalore";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=4.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item10";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Agra";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=4.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);

var data={};
data["itemName"]="Item11";
data["itemDesc"]="Very nice product of abc company";
data["city"]="Agra";
data["zip"]=560068;
data["frequency"]=70;
data["rating"]=4.4;
data["secRating"]=3.8;
data["ILDesc"]="abc def";
JsonObj.push(data);